metadata:
  source: https://git.linaro.org/lava/lava-lab.git (tests/lava_dispatcher/sample_jobs/ipxe.yaml)
  path: shared/health-checks/x86.yaml

device_type: x86-ipxe

context:
  extra_kernel_args: "console=ttyS1,115200n8 console=tty0"

job_name: x86_64 health check for zoetis smart panel (boot via ipxe)
timeouts:
  job:
    minutes: 30
  action:
    minutes: 3
  connection:
    minutes: 2

visibility: public
priority: medium

actions:
- deploy:
    timeout:
      minutes: 20
    to: tftp
    kernel:
      url: http://fileserver:8085/adlink/intel-corei7-64/bzImage-initramfs
    os: oe

- boot:
    timeout:
      minutes: 8
    method: ipxe
    commands: ramdisk
    parameters:
      shutdown-message: "reboot: Restarting system"
    prompts:
    - 'linaro-test'
    - 'root@debian:~#'
    - '/ #'
